//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaginaWebBakan.ServiceReferenceUsuarioss {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceUsuarioss.ILoginSVC")]
    public interface ILoginSVC {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginSVC/ValidarUsuario", ReplyAction="http://tempuri.org/ILoginSVC/ValidarUsuarioResponse")]
        bool ValidarUsuario(string usr, string pas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginSVC/ValidarUsuario", ReplyAction="http://tempuri.org/ILoginSVC/ValidarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> ValidarUsuarioAsync(string usr, string pas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginSVC/NombreUsuario", ReplyAction="http://tempuri.org/ILoginSVC/NombreUsuarioResponse")]
        string NombreUsuario(string usr, string pas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginSVC/NombreUsuario", ReplyAction="http://tempuri.org/ILoginSVC/NombreUsuarioResponse")]
        System.Threading.Tasks.Task<string> NombreUsuarioAsync(string usr, string pas);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoginSVCChannel : PaginaWebBakan.ServiceReferenceUsuarioss.ILoginSVC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginSVCClient : System.ServiceModel.ClientBase<PaginaWebBakan.ServiceReferenceUsuarioss.ILoginSVC>, PaginaWebBakan.ServiceReferenceUsuarioss.ILoginSVC {
        
        public LoginSVCClient() {
        }
        
        public LoginSVCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginSVCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginSVCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginSVCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ValidarUsuario(string usr, string pas) {
            return base.Channel.ValidarUsuario(usr, pas);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarUsuarioAsync(string usr, string pas) {
            return base.Channel.ValidarUsuarioAsync(usr, pas);
        }
        
        public string NombreUsuario(string usr, string pas) {
            return base.Channel.NombreUsuario(usr, pas);
        }
        
        public System.Threading.Tasks.Task<string> NombreUsuarioAsync(string usr, string pas) {
            return base.Channel.NombreUsuarioAsync(usr, pas);
        }
    }
}
